### PR TITLE
Added support for WriteHttp plugin

### LINKED ISSUE #5: Collectd http write plugin
I would like to request development of a plugin compatible with Write_HTTP.

https://collectd.org/wiki/index.php/Plugin:Write_HTTP

### PR DESCRIPTION
**Pull request by yogeswaran**
This fixes #5

### CODE REVIEW

**Comment by niklibrato** [comment]
OMG so excited :)
How would I do simple authentication? Can do something like
`<Node Name="example-node-1" Url="http://login:password@mydomain.com">
      <roxy Enable="false" Url="" />
</Node>`

**Comment by yogeswaran** [comment]
authentication is not supported now, see https://github.com/bloomberg/collectdwin/wiki/WriteHttp-plugin#writehttp-plugin for available configurations.

It is easy to add authentication, what would you like to have (username/password)?

**Comment by niklibrato** [comment]
Yes that would be awesome. The Linux collectd configuration supports the following format:

`<Plugin write_http>
        <URL "https://collectd.librato.com/v1/measurements">
            User "nik@librato.com"
            Password "secretpassword"
            Format "JSON"
        </URL>
</Plugin>`

Allowing a similar format in CollectdWin would be awesome. Maybe something like this?

`<Node Name="librato" Url="https://collectd.librato.com/v1/measurements" User="nik@librato.com" Password="supersecret">  
</Node>`

**Comment by niklibrato** [comment]
looks like https://github.com/bloomberg/collectdwin/pull/20 takes care of the auth and more.

**Pull request merged**
